### ISSUE TITLE
Auto dose potions to (4)

### ISSUE THREAD

**Issue by wgh5** [oldschoolgg/obdocs#107]
Can we get an option to automatically turn (1),(2),& (3) doses into (4)? We need them for so many activities and manually creating (4) doses is annoying af.

Example: 
Me: /k :zilyana:
@Me,  :minion: Bot Me finished killing 19 Commander Zilyana. Your Commander Zilyana KC is now 3,256.
XP Gains: +103,665 :attack: +103,665 :strength: +103,665 :defence: +103,405 :hitpoints:

Messages: **Mixed 12 Saradomin Brew (3) into 9 Saradomin Brew (4), 6 Magic Potion (3) into 4 Magic Potions (4) and 1 Magic Potion (2)**. Caught an impling, you received: 1x Ninja impling jar, :mysterybox: You received 2x loot and 1x Untradeable Mystery Box., :harry:: 58x Banana. 

**Also! (I dont know the command) /combine :potion: :all: :(4):**

**Comment by 000000653** [comment]
This issue tracker is for the wiki, you should post suggestions or bugs for the bot on the bot's issue tracker here: https://github.com/oldschoolgg/oldschoolbot
