### ISSUE TITLE
Thieving is broken

### ISSUE THREAD

**Issue by ordinaryId** [oldschoolgg/obdocs#73]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
Everyone got notified that pets were broken. I've been doing thieving for a few days. This morning when pets broke. I sent my trip with wilvus 2 times with no return. Tried again without wilvus equipped and my trip still did not return. =m shows I'm doing nothing after the time is up

**Comment by osrsolympus** [comment]
Issue for oldschoolgg/oldschool bot not /obdocs

**Comment by ordinaryId** [comment]
Plunder works. But pickpocketing vyres is what is messed up
