### ISSUE TITLE
Bloodshard may be iffy

### ISSUE THREAD

**Issue by ordinaryId** [oldschoolgg/obdocs#74]
## 🐛 Bug Report

I've been receiving 3x blood shard ever now and then while pickpocketing from vyres. After the pets broke and it was impossible for a trip to return. Now that it is fixed. I have received 3x blood shard from 1 trip. The next trip was 9x blood shard. I don't know if there is something going on. Or I just got lucky.

@Shaggy,  emeraldMinion Scooby Doo finished pickpocketing a Vyre 1375x times, due to failures you missed out on 625x pickpockets, you also received 421,987.5 XP (1,265,962.5 XP/Hr).

You received: 486x Death rune, 216x Blood rune, 964,350x Coins, 45x Diamond, 156x Uncut ruby, 189x Blood pint, 9x Blood shard, 18x Cooked mystery meat.
Say ​y​‍ to repeat this trip.
wilvus Wilvus did some pickpocketing during this trip and got you: 321,568x Coins, 45x Tokkul, 9x Krandorian seed, 7x Barley seed, 7x Potato seed, 4x Jute seed, 1x Nasturtium seed, 1x Hammerstone seed, 1x Tomato seed.

**Comment by ReZeroed** [comment]
just lucky my man, armband gives 3x loot so getting a drop of 9 means you got 3 in one trip, and while that is rare, it's not that uncommon either.

**Comment by ordinaryId** [comment]
Thank you zero
