### ISSUE TITLE
Hunter master cape + sandy does not work

### ISSUE THREAD

**Issue by Fartplox** [oldschoolgg/obdocs#79]
It lists that Sandy doubles loot and shows the loot correctly, but you only receive half that amount. It is likely Sandy is not working as shown. Thank you!
![Screenshot_20210324-213241_Discord](https://user-images.githubusercontent.com/81340823/112410932-06d83280-8cea-11eb-9e32-752a7278f2f3.jpg) 
![Screenshot_20210324-213243_Discord](https://user-images.githubusercontent.com/81340823/112410964-16f01200-8cea-11eb-9474-7c0c10bd2ab1.jpg)

**Comment by thievious1** [comment]
posted bug in the wrong place, closing on his behalf as it was reported correctly :)
