### ISSUE TITLE
Grandmaster clues

### ISSUE THREAD

**Issue by ordinaryId** [oldschoolgg/obdocs#80]
## 🐛 Bug Report

I am assuming something is going on with clues . I sent a trip for 1 clue that told me a time of 6 minutes. It turned into 13 minutes. I'm not sure if a bug or not. I was just told to report.
![Screenshot_20210403-101812](https://user-images.githubusercontent.com/68664696/113483007-d2414500-9466-11eb-842a-a7c55dc88ab3.png)

**Comment by JerMous3** [comment]
Bot got rebooted, which caused the trip time going up issue. Sorry to say Shaggy, but u lost a gm because u have to cancel now :|

**Comment by ordinaryId** [comment]
![Screenshot_20210403-102728](https://user-images.githubusercontent.com/68664696/113483131-83e07600-9467-11eb-9f4d-bac7119c2d99.png)
Even if it restarted. Do I have to cancel. Now it's saying 13 minutes at least

**Comment by ordinaryId** [comment]
My time just kept rising so I canceled. Thank you for helping :)
