### ISSUE TITLE
[ATTN: MAGNABOY] Ability to disable commands per channel, and/or redirect to another channel for admins on other servers. (pics inside)

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/obdocs#81]
## 🚀 Feature Proposal

Hey Magna,

So I noticed on the command list on the website for server admins there are 2 commands 1 to disable seperate commands for whole server and 1 to disable the bot completely per channel. 
![SmartSelect_20210504-012147_Chrome.jpg](https://user-images.githubusercontent.com/68685674/116967142-472ab900-ac77-11eb-9982-21f50ddd2003.jpg)

on the main server, when non t5 try to send money, trade items or even gamble, it redirects to the correct channel.
![SmartSelect_20210504-011943_Discord.jpg](https://user-images.githubusercontent.com/68685674/116967234-77725780-ac77-11eb-8100-e5eaa900f497.jpg)

would there be any possible way you can make this a command available for server admins only on other servers? would do a lot of good. for example: disable farming commands and redirect them to a farming channel (if that's set up on the person's server). same for masses and raids.. 

also the ability to enable custom tags to a role, so only a person with such role could use such tag. and so on. because right now I got a server that has tags to ping certain roles, and one role that is allowed to use @ roles but everyone is still able to use that tag. (I hope this makes sense)

look forward to hearing any response on this subject. thanks for taking the time to read this.

**Comment by AvariceBrah** [comment]
Clarification of last part;
=Tag add bnightmare @bsomass a nightmare mass is occuring shortly! Be ready!

Is there a way to =tag disable bnightmare @role
