### ISSUE TITLE
Achievement diary update messed up my =AD claim

### ISSUE THREAD

**Issue by dtafc123** [oldschoolgg/obdocs#94]
I included screebshots but since the most recent update which shows which skills,etc you need left for Achievement diary my AD claim doesn't actually let me claim a lamp just shows requirements for next tier. 
![Screenshot_20210804-100204_Discord](https://user-images.githubusercontent.com/88467015/128275373-385bbed9-853a-44cb-81d7-7d01d48bec13.jpg)
![Screenshot_20210804-100217_Discord](https://user-images.githubusercontent.com/88467015/128275374-531cd577-8da9-4c30-b517-2e9a43cb3bf5.jpg)
![Screenshot_20210804-100307_Discord](https://user-images.githubusercontent.com/88467015/128275375-7ecec530-15c2-4547-8b4f-0c904496a5b6.jpg)
![Screenshot_20210804-100342_Discord](https://user-images.githubusercontent.com/88467015/128275377-942ed712-d826-4f0b-bd05-c8ab67bf88e4.jpg)

**Comment by eggaroonie** [comment]
this is the repository for the wiki, please report this to the actual bot repositoryhttps://github.com/oldschoolgg/oldschoolbot/issues/new?labels=feature+request&template=bug.md
