### ISSUE TITLE
Update Dwarven Knife boost info

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/obdocs#96]
so it was posted that `- Thanks to` @kevinsmendes `you now get a 2x fletching boost for dwarven knife`

I was hoping this could be added to the wiki instead of `no boost`![Screenshot_20210822-214229_Chrome.png](https://user-images.githubusercontent.com/68685674/130382826-a6df7b10-273a-4c0f-ba86-afbdc05dea46.png)

**Comment by eggaroonie** [comment]
fixed, ty :)
